import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('/workspace/artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error') console.log('console:',m.text());});
page.setDefaultTimeout(60000);await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.mapDiagnostics && window.mapDiagnostics().renderer.frame>3,null,{timeout:60000});
console.log('scene',await page.evaluate(()=>window.mapDiagnostics()));
await page.screenshot({path:'/workspace/artifacts/sandeul-afternoon.png'});
await page.locator('[data-time="night"]').click();await page.waitForTimeout(700);
if(await page.locator('#time-label').textContent()!=='푸른 밤')throw Error('Night control failed');
await page.screenshot({path:'/workspace/artifacts/sandeul-night.png'});
await page.setViewportSize({width:960,height:640});
await page.locator('#lights').uncheck();await page.locator('#wind').uncheck();
console.log('controls',await page.evaluate(()=>window.mapDiagnostics()));
if(await page.evaluate(()=>window.mapDiagnostics().lightsEnabled || window.mapDiagnostics().windEnabled))throw Error('Light / wind controls failed');
await page.locator('[data-time="day"]').click();
await page.locator('#exposure').fill('1.3');
if(await page.locator('#exposure-value').textContent()!=='1.30')throw Error('Exposure failed');
await page.locator('#walk').click();await page.locator('#enter-walk').click();await page.waitForTimeout(500);
console.log('walking',await page.evaluate(()=>window.mapDiagnostics()));
if(await page.evaluate(()=>window.mapDiagnostics().mode)!=='walk')throw Error('Walk failed');
await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.mapDiagnostics().camera[2]<19.95,null,{timeout:30000});await page.keyboard.up('KeyW');
if(await page.evaluate(()=>window.mapDiagnostics().camera[2])>=20)throw Error('Movement failed');
await page.keyboard.press('Escape');await page.waitForFunction(()=>window.mapDiagnostics().mode==='orbit');
await page.locator('#orbit').click();
await page.setViewportSize({width:390,height:844});await page.locator('[data-time="golden"]').click();await page.screenshot({path:'/workspace/artifacts/sandeul-mobile.png'});
console.log('errors',errors);if(errors.length)throw Error(errors.join('\n'));
await browser.close();console.log('PASS: rendered scene, time, lights, wind, exposure, walking, movement and mobile layout');
